### ISSUE TITLE
can´t send messages 

### ISSUE THREAD

**Issue by jcbelair** [vilm3r/sendstr-web#3]
there is no send button.. using brave for MAc

**Comment by vilm3r** [comment]
It will automatically send once you type into the text field. If it's still not working for you please submit a bug report with details so I can reproduce the issue.

**Comment by jcbelair** [comment]
it works… its more like a live chat… one side writes the other sees but can’t reply.. did not understand that before

Email: ***@***.***
Oficina: 5250-1640, 2708
Celular: 044-555404-3569
http://www.spiralis.com.mx
