### ISSUE TITLE
Not able to send from computer to mobile

### ISSUE THREAD

**Issue by shankargopal** [vilm3r/sendstr-web#5]
**Describe the bug**
Thanks so much for this intriguing application of Nostr!

I'm having trouble sending from laptop to mobile.  On Firefox on my laptop, I am able to receive, but not able to send to Firefox on my mobile, as the "Copy pubkey" page simply stays forever on the mobile when attempting to receive. 

**To Reproduce**
1. Go to https://sendstr.com on Firefox on Android.
2. Click on "Receive"
3. Tap "Copy pubkey"
4. Send pubkey to myself in some messaging app
5. Cut and paste pubkey into sendstr.com on laptop after clicking "Send"
6. Wait indefinitely on mobile for page to transition to text box.  It does not transition, so no sending from laptop is possible. 

**Expected behavior**
A transition to a page with a text box so text can be received.

**Desktop (please complete the following information):**
 - OS: `Linux debian 5.18.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux`
 - Browser: Firefox
 - Version: 107.0.1

**Smartphone (please complete the following information):**
 - Device: Nokia
 - OS: Android 12
 - Browser: Firefox Nightly
 - Version: 110.0a1

**Additional context**

**Comment by vilm3r** [comment]
I'm not able to reproduce. Is it possible that the copied pubkey has spaces? I'll add a trim to the input so it'll automatically remove erroneous characters.
